### PR TITLE
Recalbox 4.1.x fixed maxtemp and updated

### PR DESCRIPTION
**Pull request by rockaddicted**
- Fixed issue #1034 - max temperature is nor more available on 4.1
- Added missing systems
- Removed download links

### CODE REVIEW

**Comment by sveetch** [comment]
@rockaddicted seems "Removed download links" is related to #69 , how do you manage this with final user ? you publish links from forum or irc on demand ?

**Comment by rockaddicted** [comment]
@sveetch We don't provides anymore any kinds of links with copyrighted content. Final user will have to find them by himself.

**Comment by sveetch** [comment]
Does the 4.1 version is a stable/final release ? (aka not a beta/RC)

**Comment by rockaddicted** [comment]
A public unstable version will be released in the next days. So theses modifications should be merged before.

**Pull request merged**
