### PR TITLE
[fix] use gunicorn has a production server and fix wrong repo project path 

### PR DESCRIPTION
**Pull request by 4383**
Hello guys,

This is just a minimal fix for your documentation and installer for clone or download project from the right repository without http redirect for users

### CODE REVIEW

**Comment by 4383** [comment]
Django command runserver is a development server run this command on a production machine is not recommanded.
You must use gunicorn instead of django command runserver.
runserver expose you to DDOS/DOS attack and many others kinds of attacks if user expose recalbox-manager over http on internet or over an insecure network.

**Comment by 4383** [comment]
Improve Makefile maintenance by generating help message dynamically for each target.
Never maintain a global helping message, just write a target comment (target documentation or target explain in other words) and reuse it on generated global helping message

**Comment by 4383** [comment]
If my pull request is accepted the recalbox-buildroot project must be updated for integrate gunicorn launch instead of django runserver launch.

https://github.com/recalbox/recalbox-buildroot/blob/master/board/recalbox/fsoverlay/etc/init.d/S94manager

I can propose a patch to you when this pull request will be done.

**Comment by sveetch** [comment]
Yeah django development server is not the best thing but as documented here https://github.com/recalbox/recalbox-manager#caveats we were not able to install everything on recalbox like on a real linux box, you may see with the recalbox team directly to talk about gunicorn install.

**Pull request closed without merging**
