### PR TITLE
New recalbox.log path

### PR DESCRIPTION
**Pull request by benutzer193**

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
@sveetch i merge that to test the 4x branch

**Comment by benutzer193** [comment]
@digitalLumberjack 

Is it possible to build using the branch name? I read in the readme you should use tag or specific commit ID: https://github.com/recalbox/recalbox-buildroot/blob/054ef98a0e73bb1b6dfcfacd565642b888541a36/docs/manual/adding-packages-tips.txt

If yes, I can delete this issue:
https://github.com/recalbox/recalbox-manager/issues/53

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-buildroot/commit/39ff0d767321645effef0ebeeb7fa1ec57d38f35 answer your question :)

**Comment by benutzer193** [comment]
@digitalLumberjack yes I already saw, that's why I asked :D
Thanks :)

**Pull request merged**
