### PR TITLE
Set the right recalbox.log path

### PR DESCRIPTION
**Pull request by substring**
Something went wrong with my previous PR ...

### CODE REVIEW

**Comment by sveetch** [comment]
Is this and #54 are for Recalbox 3.x ? Because master branch is actually for 3.x

**Comment by substring** [comment]
It's indeed for 4.0.0. Have i missed my pr ?

Le sam. 6 févr. 2016 11:55, David THENON notifications@github.com a
écrit :

**Comment by sveetch** [comment]
Not the PR itself, just should have not merged it to master and not you, @digitalLumberjack is the guilty one :)

**Comment by substring** [comment]
@digitalLumberjack or @sveetch 
Can one of you revert this PR and merge it to the recalbox_4.x.x branch ?

**Comment by substring** [comment]
@digitalLumberjack as proven on https://github.com/recalbox/recalbox-os/issues/588#issuecomment-182327831 Merge this PR to the recalbox_4-x branch, unless you build recalbox with another branch

**Comment by digitalLumberjack** [comment]
O damn

**Comment by digitalLumberjack** [comment]
Ok it's allright now. Sorry for the fails.

**Comment by substring** [comment]
ok on pi0 and pi2
@digitalLumberjack You can close

**Pull request merged**
